[package]
name = "tree_hash"
description = "Efficient Merkle-hashing as used in Ethereum consensus"
documentation = "https://docs.rs/tree_hash"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
alloy-primitives = { version = "1", default-features = false }
ethereum_hashing = { version = "0.8", default-features = false, features = ["zero_hash_cache"]  }
ethereum_ssz = { version = "0.10", default-features = false }
smallvec = { version = "1", default-features = false }
typenum = { version = "1", default-features = false }

[dev-dependencies]
proptest = "1"
rand = "0.9"
tree_hash_derive = { path = "../tree_hash_derive" }
ethereum_ssz_derive = "0.10"
trybuild = "1"

[features]
default = ["std", "ring"]
std = ["alloy-primitives/std", "ethereum_ssz/std", "ethereum_hashing/std"]
arbitrary = ["alloy-primitives/arbitrary"]
ring = ["ethereum_hashing/ring"]
sha2 = ["ethereum_hashing/sha2"]
